import { Animal } from '../models/animal.model';

export const ANIMAUX: Animal[] = [
  { espece: 'Lion', name: 'Roi de la Jungle', picture: 'assets/images/concombre.png' },
  { espece: 'Éléphant', name: 'Le plus grand animal terrestre', picture: 'assets/images/concombre.png' },
  { espece: 'Tigre', name: 'Félin féroce', picture: 'assets/images/concombre.png' },
  { espece: 'Girafe', name: 'Le mammifère le plus grand', picture: 'assets/images/concombre.png' },
  { espece: 'Zèbre', name: 'Cheval rayé', picture: 'assets/images/concombre.png' },
  { espece: 'Kangourou', name: 'Marsupial sauteur', picture: 'assets/images/concombre.png' },
  { espece: 'Panda', name: 'Mangeur de bambou', picture: 'assets/images/concombre.png' },
  { espece: 'Pingouin', name: 'Oiseau sans vol', picture: 'assets/images/concombre.png' },
  { espece: 'Gorille', name: 'Géant doux', picture: 'assets/images/concombre.png' },
  { espece: 'Guépard', name: 'L\'animal terrestre le plus rapide', picture: 'assets/images/concombre.png' },
  { espece: 'Rhinocéros', name: 'Herbivore à corne', picture: 'assets/images/concombre.png' },
  { espece: 'Hippopotame', name: 'Cheval de rivière', picture: 'assets/images/concombre.png' },
  { espece: 'Crocodile', name: 'Prédateur ancien', picture: 'assets/images/concombre.png' },
  { espece: 'Flamant', name: 'Oiseau rose', picture: 'assets/images/concombre.png' },
  { espece: 'Paon', name: 'Étalage coloré', picture: 'assets/images/concombre.png' },
  { espece: 'Koala', name: 'Mangeur d\'eucalyptus', picture: 'assets/images/concombre.png' },
  { espece: 'Léopard', name: 'Chasseur furtif', picture: 'assets/images/concombre.png' },
  { espece: 'Orang-outan', name: 'Habitat de la forêt', picture: 'assets/images/concombre.png' },
  { espece: 'Paresseux', name: 'Mouvement lent', picture: 'assets/images/concombre.png' },
  { espece: 'Renard polaire', name: 'Manteau blanc d\'hiver', picture: 'assets/images/concombre.png' },
  { espece: 'Loup', name: 'Chef de meute', picture: 'assets/images/concombre.png' },
  { espece: 'Ours', name: 'Géant de la forêt', picture: 'assets/images/concombre.png' },
  { espece: 'Suricate', name: 'Sentinelle alerte', picture: 'assets/images/concombre.png' },
  { espece: 'Toucan', name: 'Bec lumineux', picture: 'assets/images/concombre.png' },
  { espece: 'Autruche', name: 'Le plus grand oiseau', picture: 'assets/images/concombre.png' },
  { espece: 'Raton laveur', name: 'Éboueur masqué', picture: 'assets/images/concombre.png' },
  { espece: 'Cerf', name: 'Pâtre gracieux', picture: 'assets/images/concombre.png' },
  { espece: 'Renard', name: 'Prédateur rusé', picture: 'assets/images/concombre.png' },
  { espece: 'Bison', name: 'Grand pâtre des plaines', picture: 'assets/images/concombre.png' },
  { espece: 'Chameau', name: 'Voyageur du désert', picture: 'assets/images/concombre.png' },
  { espece: 'Caméléon', name: 'Changeur de couleur', picture: 'assets/images/concombre.png' },
  { espece: 'Dauphin', name: 'Nageur intelligent', picture: 'assets/images/concombre.png' },
  { espece: 'Aigle', name: 'Oiseau majestueux de proie', picture: 'assets/images/concombre.png' },
  { espece: 'Faucon', name: 'Chasseur rapide', picture: 'assets/images/concombre.png' },
  { espece: 'Gorille', name: 'Géant doux', picture: 'assets/images/concombre.png' },
  { espece: 'Faucon', name: 'Chasseur aux yeux perçants', picture: 'assets/images/concombre.png' },
  { espece: 'Iguane', name: 'Lézard vert', picture: 'assets/images/concombre.png' },
  { espece: 'Jaguar', name: 'Prédateur de la forêt', picture: 'assets/images/concombre.png' },
  { espece: 'Kangourou', name: 'Marsupial sauteur', picture: 'assets/images/concombre.png' },
  { espece: 'Lémurien', name: 'Originaire de Madagascar', picture: 'assets/images/concombre.png' },
  { espece: 'Élan', name: 'Géant de la forêt', picture: 'assets/images/concombre.png' },
  { espece: 'Narval', name: 'Licorne de la mer', picture: 'assets/images/concombre.png' },
  { espece: 'Ocelot', name: 'Chat tacheté', picture: 'assets/images/concombre.png' },
  { espece: 'Perroquet', name: 'Parleur coloré', picture: 'assets/images/concombre.png' },
  { espece: 'Quokka', name: 'Animal le plus heureux', picture: 'assets/images/concombre.png' },
  { espece: 'Serpent à sonnette', name: 'Vipère venimeuse', picture: 'assets/images/concombre.png' },
  { espece: 'Phoque', name: 'Nageur joueur', picture: 'assets/images/concombre.png' },
  { espece: 'Tigre', name: 'Félin féroce', picture: 'assets/images/concombre.png' },
  { espece: 'Urial', name: 'Mouton des montagnes', picture: 'assets/images/concombre.png' },
  { espece: 'Vautour', name: 'Oiseau charognard', picture: 'assets/images/concombre.png' },
  { espece: 'Morse', name: 'Géant arctique', picture: 'assets/images/concombre.png' },
  { espece: 'Xerus', name: 'Écureuil terrestre africain', picture: 'assets/images/concombre.png' },
  { espece: 'Yak', name: 'Bête himalayenne', picture: 'assets/images/concombre.png' },
  { espece: 'Zèbre', name: 'Cheval rayé', picture: 'assets/images/concombre.png' }
];

